# Generated by Django 4.2.11 on 2024-06-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(upload_to='posts/images/')),
                ('description', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('created_by', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'posts_post',
            },
        ),
    ]
