# Generated by Django 4.2.11 on 2024-06-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_rename_user_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
