# Generated by Django 4.2.11 on 2024-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer')], max_length=50),
        ),
    ]
